baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "SOS 598 Research Data Management"
theme = "material"
# disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


# [markup.goldmark.renderer]
# unsafe = true


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Stevan Earl"
  bio = ""
  job = "Information Manager, Central Arizona-Phoenix Long-Term Ecological Research"
  location = "Arizona State University"
  gravatarEmail = "stevan.earl@asu.edu"
  # Your profile picture
  # picture = ""
  twitter = "StevanEarl"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "syllabus"
  name = "Syllabus"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/syllabus"
[[menu.main]]
  weight = 3
  identifier = "policies"
  name = "Policies"
  pre = "<i class=\"material-icons\">gavel</i>"
  url = "/policies"
[[menu.main]]
  weight = 4
  identifier = "rstudio"
  name = "RStudio"
  pre = "<i class=\"material-icons\">cloud_queue</i>"
  url = "https://rstudio.cloud"
[[menu.main]]
  weight = 5
  identifier = "github"
  name = "GitHub"
  pre = "<i class='fab fa-github fa-lg'></i>"
  url = "https://github.com/SOS598-RDM"
[[menu.main]]
  weight = 6
  identifier = "help"
  name = "Help"
  pre = "<i class=\"material-icons\">help</i>"
  url = "https://github.com/Sta199-S18/community/issues"


[[menu.footer]]
  weight = 1
  identifier = "SOS"
  name = "School of Sustainability"
  pre = "<i class=\"button-icon fa fa-2x fa-map-marker\"></i>"
  url = "https://schoolofsustainability.asu.edu/"
[[menu.footer]]
  weight = 2
  name = "RStudio"
  pre = "<i class=\"icon-rlogo\" style=\"font-size:150%\"></i>"
  url = "https://rstudio.cloud/"
[[menu.footer]]
  weight = 3
  identifier = "GitHub"
  name = "GitHub"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/SOS598-RDM"
[[menu.footer]]


[params]
  dateFormat = "January 2, 2006"
  background = "http://www2.stat.duke.edu/courses/Spring18/Sta199/img/mugesketch.png"
  favicon = "img/favicon.ico"
